name: Build and deploy to Github pages

on:
  push:
    branches:
    - source
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm run build --if-present
      env:
        PUBLIC_URL: ''
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v2.5.1
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./build
        # optional, default is true
        # If existing files in the publish branch should be not removed before deploying
       # optional, default is false
